version: '3.1'

services:
  app:
    image: 'eba7aa952ddd'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/TaskManageSystem
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - APP_SECRET=iofgjidjgjpecslfonjgfdjbdfghouisrgosgtkvfgglibhsdfgbhsdfhuisdfvbh
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TaskManageSystem
